FROM pedromslopes/antidotedb:locks

MAINTAINER Pedro Lopes <pms.lopes@campus.fct.unl.pt>

ENV AQL_NAME "aql@127.0.0.1"

#AQL
ADD . /opt/AQL/
RUN chmod a+x /opt/AQL/erl_scripts/create_cluster.erl \
	&& chmod a+x /opt/AQL/erl_scripts/populate_index.erl

ADD dockerfiles-local/start_and_attach.sh /opt/
ADD dockerfiles-local/entrypoint.sh /

RUN chmod a+x /opt/start_and_attach.sh \
	&& chmod a+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh", "/opt/start_and_attach.sh"]
